apiVersion: v1
kind: Service
metadata:
  name: elasticsearch
  namespace: honeypot
  labels:
    app: elasticsearch
spec:
  type: ClusterIP
  selector:
    app: elasticsearch
  ports:
    - port: 9200
      targetPort: 9200
      name: http
      protocol: TCP
    - port: 9300
      targetPort: 9300
      name: transport
      protocol: TCP
