apiVersion: apps/v1
kind: Deployment
metadata:
  name: logstash
  namespace: honeypot
  labels:
    app: logstash
spec:
  replicas: 1
  selector:
    matchLabels:
      app: logstash
  template:
    metadata:
      labels:
        app: logstash
    spec:
      containers:
        - name: logstash
          image: docker.elastic.co/logstash/logstash:8.12.0
          ports:
            - containerPort: 5044
          env:
            - name: LS_JAVA_OPTS
              value: "-Xms256m -Xmx256m"
          resources:
            requests:
              cpu: 300m
              memory: 512Mi
            limits:
              cpu: 300m
              memory: 512Mi
          volumeMounts:
            - name: logstash-config
              mountPath: /usr/share/logstash/config/logstash.yml
              subPath: logstash.yml
            - name: logstash-config
              mountPath: /usr/share/logstash/config/pipelines.yml
              subPath: pipelines.yml
            - name: logstash-config
              mountPath: /usr/share/logstash/pipeline/main.conf
              subPath: main.conf
      volumes:
        - name: logstash-config
          configMap:
            name: logstash-config
