apiVersion: v1
kind: Service
metadata:
  name: postgres-gateway
  namespace: honeypot
  labels:
    app: postgres-gateway
spec:
  type: ClusterIP
  selector:
    app: postgres-gateway
  ports:
    - port: 5432
      targetPort: 5432
      protocol: TCP
