apiVersion: v1
kind: Service
metadata:
  name: honeypot-generic
  namespace: honeypot
  labels:
    app: honeypot-generic
spec:
  type: ClusterIP
  selector:
    app: honeypot-generic
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: honeypot-exploits
  namespace: honeypot
  labels:
    app: honeypot-exploits
spec:
  type: ClusterIP
  selector:
    app: honeypot-exploits
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: honeypot-fuzzers
  namespace: honeypot
  labels:
    app: honeypot-fuzzers
spec:
  type: ClusterIP
  selector:
    app: honeypot-fuzzers
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: honeypot-dos
  namespace: honeypot
  labels:
    app: honeypot-dos
spec:
  type: ClusterIP
  selector:
    app: honeypot-dos
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: honeypot-recon
  namespace: honeypot
  labels:
    app: honeypot-recon
spec:
  type: ClusterIP
  selector:
    app: honeypot-recon
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: honeypot-analysis
  namespace: honeypot
  labels:
    app: honeypot-analysis
spec:
  type: ClusterIP
  selector:
    app: honeypot-analysis
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: honeypot-backdoor
  namespace: honeypot
  labels:
    app: honeypot-backdoor
spec:
  type: ClusterIP
  selector:
    app: honeypot-backdoor
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: honeypot-shellcode
  namespace: honeypot
  labels:
    app: honeypot-shellcode
spec:
  type: ClusterIP
  selector:
    app: honeypot-shellcode
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
---
apiVersion: v1
kind: Service
metadata:
  name: honeypot-worms
  namespace: honeypot
  labels:
    app: honeypot-worms
spec:
  type: ClusterIP
  selector:
    app: honeypot-worms
  ports:
    - port: 8000
      targetPort: 8000
      protocol: TCP
